services:
  api:
    build:
      context: ./api-service/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/hdb_resale?sslmode=disable
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api-service/:/app:rw
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hdb_resale
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  import-csv:
    build:
      context: ./api-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/hdb_resale?sslmode=disable
    volumes:
      - ./api-service/ResaleFlatPrices:/data/csvs:ro
    command: ["python", "scripts/import_resale_csv.py"]
volumes:
  pgdata:
